/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:e2536688-2ad4-4830-87b3-9d7419bd9de5",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_s6QRKZe8O",
    "aws_user_pools_web_client_id": "6riik45r9tqt0bne8jiall3uou",
    "oauth": {}
};


export default awsmobile;
